// Rewrite the instructions in your own words

// Write the objectives and the tests

// Write the pseudocode

define var paper var scissors var rock

difine relationship rock > scissors, paper > rock, scissors > paper

ask user to choose between the 3 diffrenet variables

make program randomly select one of the 3 variables

repeat 3 times

print winner and scores

// paste your JS generated by blockly below here
